services:
  product-db:
    image: mysql:8.0
    container_name: product-mysql
    environment:
      MYSQL_DATABASE: minimarket_product_db
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_USER: product_user
      MYSQL_PASSWORD: product_password
    ports:
      - "3307:3306"
    volumes:
      - product-db-data:/var/lib/mysql
    networks:
      - mini-market-network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-redis:
    image: redis:7-alpine
    container_name: product-redis
    ports:
      - "6380:6379"
    volumes:
      - product-redis-data:/data
    networks:
      - mini-market-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  product-db-data:
    driver: local
  product-redis-data:
    driver: local

networks:
  mini-market-network:
    driver: bridge