server:
  port: 8080

spring:
  application:
    name: account-service


  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: account-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      acks: all
      retries: 3

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    open-in-view: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:account-redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

logging:
  level:
    root: INFO
    com.minimart: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

jwt:
  secret: 1fed56241e80f07310227d1529dd928087620bf836eed6802d1843197db83501
  access-token-validity: 3600000
  refresh-token-validity: 604800000

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: ${SPRING_ZIPKIN_BASE_URL:http://zipkin:9411}/api/v2/spans