server:
  port: 8080

spring:
  application:
    name: account-service

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: account-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      acks: all
      retries: 3

  datasource:
    url: jdbc:mysql://localhost:3306/minimarket_account_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: account_user
    password: account_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: 1fed56241e80f07310227d1529dd928087620bf836eed6802d1843197db83501
  access-token-validity: 3600000  # 1시간
  refresh-token-validity: 604800000  # 7일