spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3306/minimarket_account_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: account_user
    password: account_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: 1fed56241e80f07310227d1529dd928087620bf836eed6802d1843197db83501
  access-token-validity: 3600000  # 1시간
  refresh-token-validity: 604800000  # 7일