services:
  shipping-db:
    image: mysql:8.0
    container_name: shipping-mysql
    environment:
      MYSQL_DATABASE: minimarket_shipping_db
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_USER: shipping_user
      MYSQL_PASSWORD: shipping_password
    ports:
      - "3310:3306"
    volumes:
      - shipping-db-data:/var/lib/mysql
    networks:
      - mini-market-network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

#  shipping-redis:
#    image: redis:7-alpine
#    container_name: shipping-redis
#    ports:
#      - "6382:6379"
#    volumes:
#      - shipping-redis-data:/data
#    networks:
#      - mini-market-network
#    command: redis-server --appendonly yes
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

volumes:
  shipping-db-data:
    driver: local
#  shipping-redis-data:
#    driver: local

networks:
  mini-market-network:
    driver: bridge